services:
  soundcloud-parser:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: soundcloud_parser_app
    restart: unless-stopped
    environment:
      - BATCH_SIZE=100
      - DESIRED_POOL_WORKERS=9
      - NUM_POOL_WORKERS_SPECIFICALLY_WITHOUT_PROXY=4
    volumes:
      - ./users_test.txt:/app/users_test.txt:ro
      - ./working_proxies.txt:/app/working_proxies.txt:ro
      - ./output_on_host:/app/output_files